/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.mdiAdministrador;

import Registros.RegistroAdelanto;
import Usuarios.Administrador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jezer
 */
public class AdministrarAdelantos extends javax.swing.JInternalFrame {
    
    private Administrador administrador;
    private Integer numRegistro = null;
    private Solicitudes solicitudes;

    /**
     * Creates new form AdministrarAdelantos
     */
    public AdministrarAdelantos(Administrador administrador, Solicitudes solicitudes) {
        this.administrador = administrador;
        this.solicitudes = solicitudes;
        initComponents();
    }
    
    public void setRegistro(int num) {
        Planilla.PlanillaPago planilla = this.administrador.getPlanillaPago();
        ArrayList<RegistroAdelanto> array = planilla.getTablaAdelantos().getTabla();
        
        RegistroAdelanto adelanto = null;
        for (RegistroAdelanto registro : array) {
            if (registro.getNum() == num) {
                adelanto = registro;
                break;
            }
        }
        if (adelanto == null) return;
        
        this.empleadoTF.setText(adelanto.getEmpleado().getNombre() + ": " + adelanto.getEmpleado().getId());
        this.montoTF.setText("" + adelanto.getAdelanto());
        this.justificacionTF.setText(adelanto.getJustificacion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelID = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        empleadoLb = new javax.swing.JLabel();
        montoLb = new javax.swing.JLabel();
        justificacionLb = new javax.swing.JLabel();
        empleadoTF = new javax.swing.JTextField();
        montoTF = new javax.swing.JTextField();
        justificacionTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        labelID.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelID.setText("N° Registro:");

        idTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        idTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTFKeyReleased(evt);
            }
        });

        buscar.setBackground(new java.awt.Color(255, 102, 0));
        buscar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        empleadoLb.setText("Empleado:");

        montoLb.setText("Monto:");

        justificacionLb.setText("Justificación:");

        empleadoTF.setEnabled(false);

        montoTF.setEnabled(false);

        justificacionTF.setEnabled(false);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Rechazar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(justificacionLb)
                    .addComponent(montoLb)
                    .addComponent(empleadoLb)
                    .addComponent(labelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idTF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(empleadoTF)
                    .addComponent(montoTF)
                    .addComponent(justificacionTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelID)
                    .addComponent(buscar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoLb)
                    .addComponent(empleadoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montoLb)
                    .addComponent(montoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(justificacionLb)
                    .addComponent(justificacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTFKeyReleased
        
    }//GEN-LAST:event_idTFKeyReleased

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String id_str = this.idTF.getText();
        if (id_str.isBlank()) return;

        try {
            this.numRegistro = Integer.parseInt(id_str);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingresa un número", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.setRegistro(this.numRegistro);
    }//GEN-LAST:event_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.administrador.aceptarAdelanto(1, numRegistro);
        this.solicitudes.getTbSolicitud().setModel(this.solicitudes.arrayToTable());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.administrador.aceptarAdelanto(2, numRegistro);
        this.solicitudes.getTbSolicitud().setModel(this.solicitudes.arrayToTable());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JLabel empleadoLb;
    private javax.swing.JTextField empleadoTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel justificacionLb;
    private javax.swing.JTextField justificacionTF;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel montoLb;
    private javax.swing.JTextField montoTF;
    // End of variables declaration//GEN-END:variables
}
