/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaz.mdiAdministrador;

import static Interfaz.mdiAdministrador.AdministradorC.centralA;
import Planilla.PlanillaPago;
import Registros.RegistroPago;
import javax.swing.table.DefaultTableModel;

import Usuarios.Administrador;
import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author Gimena Navarrete
 */
public class RealizarPago extends javax.swing.JInternalFrame {

    private Administrador administrador;

    /**
     * Creates new form RealizarPago
     */
    public RealizarPago(Administrador administrador) {
        this.administrador = administrador;
        initComponents();
    }

    public Administrador getAdministrador() {
        return administrador;
    }

    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }

    public DefaultTableModel arrayToTable() {
        PlanillaPago planilla = this.administrador.getPlanillaPago();
        ArrayList<RegistroPago> array = planilla.getTablaPagos().getTabla();

        String[] columnas = { "Num", "Monto", "Fecha", "idEmpleado" };
        DefaultTableModel dtm = new DefaultTableModel(columnas, 0) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (RegistroPago registro : array) {
            Object[] datos = {
                registro.getNum(),
                registro.getMonto(),
                registro.getFecha(),
                registro.getEmpleado().getId(),
            };
            dtm.addRow(datos);
        }
        return dtm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbPagoScroll = new javax.swing.JScrollPane();
        tbPago = new javax.swing.JTable();
        realizarPago = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Realizar Pago");
        setMaximumSize(new java.awt.Dimension(76, 2147483647));
        setVisible(true);

        tbPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        tbPago.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tbPago.setModel(this.arrayToTable());
        tbPagoScroll.setViewportView(tbPago);

        realizarPago.setBackground(new java.awt.Color(255, 102, 0));
        realizarPago.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        realizarPago.setText("Realizar los pagos");
        realizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tbPagoScroll)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(realizarPago)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(realizarPago)
                .addGap(32, 32, 32)
                .addComponent(tbPagoScroll)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void realizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarPagoActionPerformed
        Pagar adm = new Pagar(this.administrador, this);
        AdministradorC.centralA.add(adm);
        Dimension desktopSize = centralA.getSize();
        Dimension FrameSize = adm.getSize();
        adm.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        adm.show();
        adm.toFront();
    }//GEN-LAST:event_realizarPagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton realizarPago;
    private javax.swing.JTable tbPago;
    private javax.swing.JScrollPane tbPagoScroll;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tbPago
     */
    public javax.swing.JTable getTbPago() {
        return tbPago;
    }
}
