/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaz.mdiAdministrador;

import static Interfaz.mdiAdministrador.AdministradorC.centralA;
import Planilla.PlanillaPago;
import Registros.RegistroAdelanto;
import java.awt.Dimension;

import Usuarios.Administrador;
import Usuarios.Empleado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gimena Navarrete
 */
public class Trabajadores extends javax.swing.JInternalFrame {

    private Administrador administrador;

    /**
     * Creates new form Empleados
     */
    public Trabajadores(Administrador administrador) {
        this.administrador = administrador;
        initComponents();
    }

    public Administrador getAdministrador() {
		return administrador;
	}

	public void setAdministrador(Administrador administrador) {
		this.administrador = administrador;
	}

    public DefaultTableModel arrayToTable(Integer id) {
        PlanillaPago planilla = this.administrador.getPlanillaPago();
        ArrayList<Empleado> array = planilla.getTablaEmpleados().getTabla();

        String[] columnas = { "ID", "Nombre", "Apellido", "Cargo", "Privilegios", "Contraseña" };
        DefaultTableModel dtm = new DefaultTableModel(columnas, 0) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (Empleado registro : array) {
            if (id != null && !registro.getId().equals(id)) continue;
            String privilegios = "Empleado";
            if (registro.getPrivilegios() == 1)
                privilegios = "Administrador";
            Object[] datos = {
                registro.getId(),
                registro.getNombre(),
                registro.getApellido(),
                registro.getCargo(),
                privilegios,
                registro.getContraseña(),
            };
            dtm.addRow(datos);
        }
        return dtm;
    }
    
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbEmpleadoTScroll = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();
        busqId = new javax.swing.JLabel();
        busqIdTF = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        crearEmpleado = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Empleados");
        setVisible(true);

        tbEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        tbEmpleados.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tbEmpleados.setModel(this.arrayToTable(null));
        tbEmpleadoTScroll.setViewportView(tbEmpleados);

        busqId.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        busqId.setText("Buscar por ID:");

        busqIdTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        buscar.setBackground(new java.awt.Color(255, 102, 0));
        buscar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        crearEmpleado.setBackground(new java.awt.Color(255, 102, 0));
        crearEmpleado.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        crearEmpleado.setText("Crear Empleado");
        crearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEmpleadoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton1.setText("Editar Empleado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(busqId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(busqIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(crearEmpleado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addComponent(tbEmpleadoTScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busqId)
                    .addComponent(busqIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearEmpleado)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(tbEmpleadoTScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEmpleadoActionPerformed
        crearEmpleado ce = new crearEmpleado(this.administrador, this);
        AdministradorC.centralA.add(ce);
        Dimension desktopSize = centralA.getSize();
        Dimension FrameSize = ce.getSize();
        ce.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ce.show();
        ce.toFront();
    }//GEN-LAST:event_crearEmpleadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        editarEmpleado ee = new editarEmpleado(this.administrador, this);
        AdministradorC.centralA.add(ee);
        Dimension desktopSize = centralA.getSize();
        Dimension FrameSize = ee.getSize();
        ee.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ee.show();
        ee.toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String id_str = this.busqIdTF.getText();
        if (id_str.isBlank()) return;
        Integer id;
        if (id_str.isBlank())
            id = null;
        else
            try {
                id = Integer.parseInt(id_str);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Ingresa un número", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        this.getTbEmpleados().setModel(this.arrayToTable(id));
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JLabel busqId;
    private javax.swing.JTextField busqIdTF;
    private javax.swing.JButton crearEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane tbEmpleadoTScroll;
    private javax.swing.JTable tbEmpleados;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tbEmpleados
     */
    public javax.swing.JTable getTbEmpleados() {
        return tbEmpleados;
    }
}
