/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.mdiEmpleado;


import Interfaz.Login;
import Usuarios.Empleado;

import static Interfaz.mdiAdministrador.AdministradorC.centralA;
import java.awt.Dimension;
import javax.swing.ImageIcon;



public class EmpleadoC extends javax.swing.JFrame {
    
    //public InputStream foto1 = this.getClass().getResourceAsStream("/Iconos/fondoCentral.png");
    private Empleado empleado;
    
    public EmpleadoC() {
        initComponents();
        this.setLocationRelativeTo(null);
     // cargarImagen(central,foto1);
        
        setSize(1000,700);
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/logo.png")).getImage());
    }
    
    /*public void cargarImagen(javax.swing.JDesktopPane jDesk, InputStream fileImage){
      
        try{
            BufferedImage image = ImageIO.read(fileImage);
            jDesk.setBorder(new ImagenFondo(image));
        }catch(Exception e){
            System.out.println("No hay imagen");
        }
        
    }
    */
    
    public Empleado getEmpleado() {
        return empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centralE = new javax.swing.JDesktopPane();
        logoEmp = new javax.swing.JLabel();
        barraMEmpleado = new javax.swing.JMenuBar();
        asistenciaEmp = new javax.swing.JMenu();
        adelantosEmp = new javax.swing.JMenu();
        pagosEmp = new javax.swing.JMenu();
        sobreMiEmp = new javax.swing.JMenu();
        salirEmp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        centralE.setBackground(new java.awt.Color(255, 255, 255));
        centralE.setOpaque(false);

        logoEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logo3.png"))); // NOI18N

        centralE.setLayer(logoEmp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout centralELayout = new javax.swing.GroupLayout(centralE);
        centralE.setLayout(centralELayout);
        centralELayout.setHorizontalGroup(
            centralELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centralELayout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(logoEmp)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        centralELayout.setVerticalGroup(
            centralELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centralELayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(logoEmp)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        barraMEmpleado.setBackground(new java.awt.Color(255, 169, 133));
        barraMEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        barraMEmpleado.setForeground(new java.awt.Color(255, 102, 0));
        barraMEmpleado.setMaximumSize(new java.awt.Dimension(3000000, 32769));

        asistenciaEmp.setBackground(new java.awt.Color(255, 102, 0));
        asistenciaEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar.png"))); // NOI18N
        asistenciaEmp.setText("Asistencia");
        asistenciaEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        asistenciaEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asistenciaEmpMouseClicked(evt);
            }
        });
        barraMEmpleado.add(asistenciaEmp);

        adelantosEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/completar.png"))); // NOI18N
        adelantosEmp.setText("Adelantos");
        adelantosEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        adelantosEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adelantosEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adelantosEmpMouseEntered(evt);
            }
        });
        barraMEmpleado.add(adelantosEmp);

        pagosEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/metodo-de-pago (1).png"))); // NOI18N
        pagosEmp.setText("Pagos");
        pagosEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pagosEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagosEmpMouseClicked(evt);
            }
        });
        barraMEmpleado.add(pagosEmp);

        sobreMiEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario (1) (1).png"))); // NOI18N
        sobreMiEmp.setText("Sobre mi");
        sobreMiEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        sobreMiEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobreMiEmpMouseClicked(evt);
            }
        });
        barraMEmpleado.add(sobreMiEmp);

        salirEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar-sesion.png"))); // NOI18N
        salirEmp.setText("Salir");
        salirEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        salirEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirEmpMouseClicked(evt);
            }
        });

        jMenuItem1.setText("Cerrar Sesion");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        salirEmp.add(jMenuItem1);

        jMenuItem2.setText("Salir del programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        salirEmp.add(jMenuItem2);

        barraMEmpleado.add(salirEmp);

        setJMenuBar(barraMEmpleado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(centralE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(centralE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asistenciaEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asistenciaEmpMouseClicked
        Asistencia as = new Asistencia();
        
        centralE.add(as);
        Dimension desktopSize = centralA.getSize();
        Dimension FrameSize = as.getSize();
        as.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        as.show();
        as.toFront();
    }//GEN-LAST:event_asistenciaEmpMouseClicked

    private void adelantosEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adelantosEmpMouseEntered
        // Invalido
    }//GEN-LAST:event_adelantosEmpMouseEntered

    private void adelantosEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adelantosEmpMouseClicked
        Adelantos ad = new Adelantos();
        
        centralE.add(ad);
        Dimension desktopSize = centralA.getSize();
        Dimension FrameSize = ad.getSize();
        ad.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ad.show();
        ad.toFront();
    }//GEN-LAST:event_adelantosEmpMouseClicked

    private void pagosEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagosEmpMouseClicked
        Pagos pa = new Pagos();
        centralE.add(pa);
        Dimension desktopSize = centralA.getSize();
        Dimension FrameSize = pa.getSize();
        pa.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        pa.show();
        pa.toFront();
    }//GEN-LAST:event_pagosEmpMouseClicked

    private void sobreMiEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMiEmpMouseClicked
        sobreMi sm = new sobreMi();
        
        centralE.add(sm);
        Dimension desktopSize = centralA.getSize();
        Dimension FrameSize = sm.getSize();
        sm.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        sm.show();
        sm.toFront();
    }//GEN-LAST:event_sobreMiEmpMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void salirEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirEmpMouseClicked
       //invalido
    }//GEN-LAST:event_salirEmpMouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Login lo = new Login();
        
        lo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoC().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adelantosEmp;
    private javax.swing.JMenu asistenciaEmp;
    private javax.swing.JMenuBar barraMEmpleado;
    public static javax.swing.JDesktopPane centralE;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel logoEmp;
    private javax.swing.JMenu pagosEmp;
    private javax.swing.JMenu salirEmp;
    private javax.swing.JMenu sobreMiEmp;
    // End of variables declaration//GEN-END:variables
}
